### ISSUE TITLE
[questions]

### ISSUE THREAD

**Issue by nickvazz** [wtharvey2/Decide#3]
Looks like you're using a static jekyll site on GitHub Pages, I don't think you can put a server / database with those. Not sure how exactly you're deploying the the site exactly ( I assume its the standard way GitHub Pages does it?)

**Comment by wtharvey2** [comment]
I'm using the jekyll site mainly as a landing page for documentation in a non-github appearing interface. The actual functionality is completely wrapped in the two html pages (`https://wtharvey2.github.io/Decide/decideMain.html` and `.../decideQuestion.html`) and their associated js. 

So if the jekyll site gets tossed, that's not a major issue.
